### ISSUE TITLE
Follow, unfollow, follow

### ISSUE THREAD

**Issue by passi1707** [isaackogan/TikTokLive#12]
Hello,
I have a problem, when someone follows, unfollows and then follows again they are treated like a new follower. Is there any way to prevent this?
Thank you.

**Comment by isaackogan** [comment]
You need to track this on your end and ignore the event when people re-follow. The library is just sending you what TikTok sends you. They are following, unfollowing, and re-following... so you get the event again. There is no way to "prevent" this with the library, wanting to prevent it is an implementation choice that you should make on your end. 

I recommend a database solution since caching can get pretty size-intensive for large streamers & only works as long as the instance is running, unless you use something like Redis.

Isaac
