### ISSUE TITLE
join, gift, follow, share doesn't work 

### ISSUE THREAD

**Issue by PolsatGraniePL** [isaackogan/TikTokLive#28]
![image](https://user-images.githubusercontent.com/88681446/168438324-2a1496d5-7277-43bf-a7e7-ce84f9435864.png)

**Comment by isaackogan** [comment]
Google "type hinting" in Python for more information.

You need to import the class "JoinEvent", "ShareEvent", etc. See the examples folder for working examples.

From the information you've given me, the events work, you just didn't import the type hinted classes.

Isaac

**Comment by PolsatGraniePL** [comment]
a no tak, zapomniałem o tym jednym szczególe....

**Comment by PolsatGraniePL** [comment]
szkoda ,że nie można wszystkiego zaimportować jednym `*`

**Comment by isaackogan** [comment]
> szkoda ,że nie można wszystkiego zaimportować jednym `*`

You can :p

**Comment by PolsatGraniePL** [comment]
a rzeczywiście, wcześnie nie działało mi. przepraszam.

jeszcze jedno pytanie.
is there a list of gifts names?

**Comment by isaackogan** [comment]
No, there is not. Please read the documentation. The client object contains an "available gifts" property with a dictionary containing all available gifts.

Please use English, by the way, even if you need to use Google Translate, so that other people can read your messages in this thread without having to translate themselves.
