### ISSUE TITLE
Nothing Still Happens. It's like it gets saved into a buffer and gets spammed in one go after restarting the library.

### ISSUE THREAD

**Issue by koffeemate** [isaackogan/TikTokLive#82]
**Describe the bug**
Nothing happens. But if you restart the library after the previous start, it will spam all the events in one go. Then nothing happens again.

**To Reproduce**
1.) Run library with unique_ID and session_ID and websocket set to false
2.) Nothing happens
3.) Restart the library (And notice everything that happened before during the duration where nothing happens gets spammed)
4.) Nothing happens again

**Comment by isaackogan** [comment]
Right on,

This will be frustrating to hear but I do not believe it is possible to run without the websocket anymore. TikTok started requiring signatures a while back and using a session id was a way to get around needing those signatures. Nowadays, it seems that a sessionid does **not** bypass the need for a signature.

Since we do not deliver signatures anymore, you are left with having to sign your own URLs and modify the library to support that, or to use websockets.

I cannot do anything about this, I am sorry.

Isaac

**Comment by isaackogan** [comment]
I want to add: When you initially start a connection, there are INITIAL events that come with that. This is why it seems like a buffer. It is. But since you are not using websocket & do not have a properly signed URL, further polling requests yield empty payloads.
